config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  root 'welcome#index'
  devise_for :users
  resources :scores
  resources :courses, only: [ :index, :show ]
  resources :faculties, only: [ :show ]
  resources :students do
    collection do
      get 'search'
      post 'search', action: :result
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
  has_many :scores
  has_many :students, through: :scores
end

app/models/faculty.rb
class Faculty < ApplicationRecord
  has_many :students
end

app/models/score.rb
class Score < ApplicationRecord
  belongs_to :student
  belongs_to :course
end

app/models/student.rb
class Student < ApplicationRecord
  belongs_to :faculty
  has_one_attached :photo
  has_many :scores
  has_many :courses, through: :scores
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  def index
    @courses = Course.all
  end

  def show
    @course = Course.find(params[:id])
  end
end

app/controllers/faculties_controller.rb
class FacultiesController < ApplicationController
  def show
    @faculty = Faculty.find(params[:id])
    @students = @faculty.students
  end
end

app/controllers/scores_controller.rb
class ScoresController < ApplicationController
  before_action :set_score, only: [:show, :edit, :update, :destroy]

  # GET /scores
  # GET /scores.json
  def index
    @scores = Score.all
  end

  # GET /scores/1
  # GET /scores/1.json
  def show
  end

  # GET /scores/new
  def new
    @score = Score.new
  end

  # GET /scores/1/edit
  def edit
  end

  # POST /scores
  # POST /scores.json
  def create
    @score = Score.new(score_params)

    respond_to do |format|
      if @score.save
        format.html { redirect_to @score, notice: 'Score was successfully created.' }
        format.json { render :show, status: :created, location: @score }
      else
        format.html { render :new }
        format.json { render json: @score.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /scores/1
  # PATCH/PUT /scores/1.json
  def update
    respond_to do |format|
      if @score.update(score_params)
        format.html { redirect_to @score, notice: 'Score was successfully updated.' }
        format.json { render :show, status: :ok, location: @score }
      else
        format.html { render :edit }
        format.json { render json: @score.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /scores/1
  # DELETE /scores/1.json
  def destroy
    @score.destroy
    respond_to do |format|
      format.html { redirect_to scores_url, notice: 'Score was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_score
      @score = Score.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def score_params
      params.require(:score).permit(:student_id, :course_id, :score)
    end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :destroy]

  # GET /students
  # GET /students.json
  def index
    @students = Student.all
  end

  # GET /students/1
  # GET /students/1.json
  def show
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students
  # POST /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: 'Student was successfully created.' }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1
  # PATCH/PUT /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to @student, notice: 'Student was successfully updated.' }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url, notice: 'Student was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  # GET /students/search
  def search
  end

  # POST /students/search
  def result
    @students = Student.joins(:scores).where('course_id = ? AND score = ?', params[:course], params[:score])
    render :index
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def student_params
      params.require(:student).permit(:name, :faculty_id, :grade, :photo)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/faculties_helper.rb
module FacultiesHelper
end

app/helpers/scores_helper.rb
module ScoresHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/courses/index.html.erb
<h1>Courses#index</h1>

<table>
  <thead>
    <tr>
      <th>科目名</th>
      <th>単位</th>
      <th></th>
      <th></th>
    </tr>
  </thead>

app/views/courses/show.html.erb
<h1>Courses#show</h1>

<p>
  <strong>科目名：</strong>
  <%= @course.name %>
</p>

<p>
  <strong>単位数：</strong>
  <%= @course.credit %>
</p>

<p>
  <% if @course.compulsory %>
    <strong>必修科目</strong>
  <% else %>
    <strong>選択科目</strong>
  <% end %>
</p>

<%= link_to 'Back', course_path %>

app/views/faculties/show.html.erb
<h1>Faculties#show</h1>
<p><b><%= @faculty.name %></b></p>

<table>
  <% @students.each do |student| %>
    <tr>
      <td><%= student.id %></td>
      <td><%= student.name %></td>
    </tr>
  <% end %>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>School</title>
    <meta charset="UTF-8">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>

    <div>
      <%= image_tag 'http://www.sfc.keio.ac.jp/img/logo.png', width: 200, style: 'margin: 20px' %>
    </div>
  </body>
</html>

app/views/scores/_form.html.erb
<%= form_with(model: score, local: true) do |form| %>
  <% if score.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(score.errors.count, "error") %> prohibited this score from being saved:</h2>

      <ul>
        <% score.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :student_id %>
    <%= form.number_field :student_id %>
  </div>

  <div class="field">
    <%= form.label :course_id %>
    <%= form.number_field :course_id %>
  </div>

  <div class="field">
    <%= form.label :score %>
    <%= form.text_field :score %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/scores/edit.html.erb
<h1>Editing Score</h1>

<%= render 'form', score: @score %>

<%= link_to 'Show', @score %> |
<%= link_to 'Back', scores_path %>

app/views/scores/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Scores</h1>

<table>
  <thead>
    <tr>
      <th>Student</th>
      <th>Course</th>
      <th>Score</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @scores.each do |score| %>
      <tr>
        <td><%= score.student_id %></td>
        <td><%= score.course_id %></td>
        <td><%= score.score %></td>
        <td><%= link_to 'Show', score %></td>
        <td><%= link_to 'Edit', edit_score_path(score) %></td>
        <td><%= link_to 'Destroy', score, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Score', new_score_path %>

app/views/scores/new.html.erb
<h1>New Score</h1>

<%= render 'form', score: @score %>

<%= link_to 'Back', scores_path %>

app/views/scores/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Student:</strong>
  <%= @score.student_id %>
</p>

<p>
  <strong>Course:</strong>
  <%= @score.course_id %>
</p>

<p>
  <strong>Score:</strong>
  <%= @score.score %>
</p>

<%= link_to 'Edit', edit_score_path(@score) %> |
<%= link_to 'Back', scores_path %>

app/views/students/_form.html.erb
<%= form_with(model: student, local: true) do |form| %>
  <% if student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
        <% student.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :faculty_id %>
    <%= form.collection_select :faculty_id, Faculty.all, :id, :name %>
  </div>

  <div class="field">
    <% for i in 1..4 %>
      <%= form.radio_button :grade, i, style: 'display: inline' %>
      <%= form.label :grade, "#{i}年", value: i, style: 'display: inline' %>
    <% end %>
  </div>

  <div class="field">
    <%= form.label :photo %>
    <%= form.file_field :photo %>
  </div>
  
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/students/edit.html.erb
<h1>Editing Student</h1>

<%= render 'form', student: @student %>

<%= link_to 'Show', @student %> |
<%= link_to 'Back', students_path %>

app/views/students/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Students</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Faculty</th>
      <th>Grade</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @students.each do |student| %>
      <tr>
        <td><%= student.name %></td>
        <td><%= student.faculty.name %></td>
	<td><%= student.grade %></td>
        <td><%= link_to 'Show', student %></td>
        <td><%= link_to 'Edit', edit_student_path(student) %></td>
        <td><%= link_to 'Destroy', student, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Student', new_student_path %>

app/views/students/new.html.erb
<h1>New Student</h1>

<%= render 'form', student: @student %>

<%= link_to 'Back', students_path %>

app/views/students/search.html.erb
<h1>成績を指定して学生を検索</h1>

<%= form_with(local: true) do |form| %>

  <div class="field">
    <%= form.label :course, '科目' %>
    <%= form.collection_select :course, Course.all, :id, :name %>
  </div>

  <div class="field">
    <%= form.label :score, '成績' %>
    <%= form.select :score, {'S' => 'S', 'A' => 'A', 'B' => 'B', 'C' => 'C', 'D' => 'D'} %>
  </div>

  <div class="actions">
    <%= form.submit '検索' %>
  </div>

<% end %>

app/views/students/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @student.name %>
</p>

<p>
  <strong>Faculty:</strong>
  <%= @student.faculty_id %>
</p>

<p>
  <% if @student.photo.attached? %>
    <%= image_tag url_for(@student.photo), height: 100 %>
  <% else %>
    No Image
  <% end %>
</p>

<%= link_to 'Edit', edit_student_path(@student) %> |
<%= link_to 'Back', students_path %>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>

<% if user_signed_in? %>
  <p>You are <%= current_user.email %></p>
  <%= link_to 'Logout', destroy_user_session_path, method: :delete %>
<% else %>
  <%= link_to 'Login', new_user_session_path %>
<% end %>